### ISSUE TITLE
Incorporate data in Releases instead of GDrive

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#18]
Leverage the use of GitHub releases to store the publicly available UNAIDS data in an accessible way.

Based on [Tan Ho's presentation](https://github.com/tanho63/project_immortality/blob/main/project_immortality_with_github.pdf) at RStudio Conf, [posted updated data](https://github.com/ffverse/ffopportunity/blob/main/update/ep_update.R) to releases (not being indexed and not counting against repo file size).

We can post data in different formats and download easily as well. Ideally posting in a compressed format for quick upload/download using `piggyback`

```
new_tag <- "v2022.07.27"
pb_new_release(tag = new_tag)

glamr::temp_folder()

readr::write_csv(df_est, file.path(folderpath_tmp, "UNAIDS_HIV_Estimates.csv"))
readr::write_csv(df_est, file.path(folderpath_tmp, "UNAIDS_HIV_Estimates.csv.gz"))
saveRDS((df_est, file.path(folderpath_tmp, "UNAIDS_HIV_Estimates.rds"))

readr::write_csv(df_tt, file.path(folderpath_tmp, "UNAIDS_TestTreat.csv"))
readr::write_csv(df_tt, file.path(folderpath_tmp, "UNAIDS_TestTreat.csv.gz"))
saveRDS((df_tt, file.path(folderpath_tmp, "UNAIDS_TestTreat.rds"))

#upload multiple files
list.files(folderpath_tmp, full.names = TRUE) %>% 
  pb_upload(tag = new_tag)

#download a specific file
pb_download(file = "UNAIDS_HIV_Estimates.csv.gz",
            dest = glamr::si_path("path_downloads"))
```

  - [ ] Use `tag` for versioning with date of release. 
  - [ ] If we are just using `piggyback` to post, we can add it as `Suggests` not `Imports` in `Description` file. If not using `piggyback` for downloading (minimize dependencies), mimic something similar to [`raw_from_url()`](https://github.com/nflverse/nflreadr/blob/8f811e34c2208e320b90e42f80823c620ad41589/R/from_url) (if using csv/csv.gz)
  - [ ] Need to test if included in a package, if we need to specify the repo in the download (`USAID-OHA_SI`)
  - [ ] Probably want to store as a compressed csv (csv.gz) for accessibility? or post both csv.gz and rds (compressed)?

@karishmas26 @tessam30

**Comment by tessam30** [comment]
@achafetz - I think we'll still need a gdrive version of the UNAIDS data for the Tableau products. These use hit the google sheet as a data source.

**Comment by achafetz** [comment]
I think that's completely reasonable. Continue leveraging the current model for Tableau (maybe in the future DDC 🙄) and we leverage GH releases for R.
