### ISSUE TITLE
Change default spoke

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#20]
Let's make the default to be PEPFAR only - `pepfar_only = TRUE`

https://github.com/USAID-OHA-SI/mindthegap/blob/592643c59322572aa86120b6272c844c4f35757f/R/pull_unaids.R#L18

**Comment by karishmas26** [comment]
[e3e33b7](https://github.com/USAID-OHA-SI/mindthegap/commit/e3e33b791c0c3e87b3f55d0079820929a2c15e13)
