### ISSUE TITLE
Add in package check

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#26]
Now that `gagglr` is live, you can add a package check to `mindthegap` so the user knows if there is a newer version of the package available.

In the `DESCRIPTION` file, add `gagglr` to `Remotes`
```
Remotes: 
    USAID-OHA-SI/gagglr
```
Add a new file under R, `R/zzz.R`
```
.onAttach <- function(...) {
  if(requireNamespace("gagglr", quietly = TRUE))
    gagglr::oha_check("mindthegap", suppress_success = TRUE)
}
```

**Comment by karishmas26** [comment]
[0dc6f86](https://github.com/USAID-OHA-SI/mindthegap/commit/0dc6f86cb0bf4cd517c92ba2778f3a0fbffc155e)
