### ISSUE TITLE
Enhance clarity of use within functions

### ISSUE THREAD

**Issue by karishmas26** [USAID-OHA-SI/mindthegap#28]
-  wrapper functions to import each dataset (import_epi_data or import_cascade_data) to pull the specific dfs rather than the parameter with the sheetname
- function to return which indicators are in which dataset to provide more clarity
- update readme
- do we need a function in mindthegap that grabs total deaths from the new data and pulls into the original output from `pull_unaids()`?

**Comment by achafetz** [comment]
OBE
