### ISSUE TITLE
Test non-standard pull EDMS Data

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#65]
testing `munge_edms` with our non standard pull

**Comment by karishmas26** [comment]
for non-standard pulls, `epi_plot()` sometimes breaks

ex) a non-standard pull of new infections / totals deaths for 15+ by sex breaks because the validating looks for indicators with "All" ages and sex

![image](https://github.com/user-attachments/assets/722a9b23-c4d8-4061-9d61-c7da47a56322)
