### ISSUE TITLE
Review code + functions

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#68]
@USAID-OHA-SI/m-crew 

- Review code itself
- Test `munge_edms` on the dataset circulated via email (re: OKR 1.4 | mindthegap)
- Test/review main functions - `load_unaids` (I did end up publishing the release other day for testing and vignette purposes),  `munge_edms`, `base_plot`, `epi_plot`

note when complete
- [x] @karishmas26 
- [x] @lbaraki 
- [x] @tessam30 
- [x] @baboyma 
- [x] @atowey-uchi

**Comment by baboyma** [comment]
Works for me. Thanks for this.

Suggestions:

1. We might need to expose read_edms() and have users do `file_data |> read_edms() |> munge_edms() |> epi_plot()`. 
2. This packages has a lot of internal functions (great to shorten workflows) that might need to be explained to advance users for custom adoptions.
