### ISSUE TITLE
missing explicit reference

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/mindthegap#9]
When I run `munge_unaids('Test & Treat', 'Integer')` I get the following error midway through (this is off the `unaids-data` branch)

![image](https://user-images.githubusercontent.com/8933069/141530082-3a119c89-8ce8-4ec7-83ac-c45b0c945eaf.png)

It looks like you are missing an explicit package reference to `dplyr`; `na_if()` --> `dplyr::na_if()`

**Comment by karishmas26** [comment]
Just added the reference! It worked on my end but let me know if it still throws the same error
